version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Car_Service_Webapp
      MYSQL_USER: webapp_user
      MYSQL_PASSWORD: carServicePass
    ports:
      - "9001:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /home/nithin/Desktop/CarServiceFullStack/database-volume:/var/lib/mysql

  backend:
    build:
      context: ./CarService
      dockerfile: Dockerfile
      network: host
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Car_Service_Webapp
      SPRING_DATASOURCE_USERNAME: webapp_user
      SPRING_DATASOURCE_PASSWORD: carServicePass
    ports:
      - "9002:8081"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./CarServiceFrontend # Path to your frontend project
      dockerfile: Dockerfile
      network: host
    ports:
      - "9003:80"
    depends_on:
      - backend

# volumes:
#   my-vol:
#     external: true
